### PR TITLE
add check_for_logical

### PR DESCRIPTION
**Pull request by yannsay-impact**

### CODE REVIEW

**Comment by mhkhan27** [comment]
I can be wrong and probably missing somethig. check_for_logical_with_list() is not working when variable_to_column  = NULL  or variable_to_column = [all value empty column]. Was it intentional?

**Comment by mhkhan27** [comment]
Bind check= false returning checked_dataset multiple times. Currently its creating nested list. From the test I can see it was intentional but probably having a single list would be better?

```
>  a |> names()
[1] "logical_xx" "logical_yy"
>  a$logical_xx |> names()
[1] "checked_dataset" "logical_xx"     
>  a$logical_yy |> names()  
[1] "checked_dataset" "logical_yy" 
```
The output i am suggesting would be like- 
```
>  a |> names()
[1] "checked_dataset", "logical_xx" "logical_yy"
```

**Comment by yannsay-impact** [comment]
- all_of :I have tried to fix it, I could not see exactly where as the warning come only once every long period.
- fixed error when "variables_to_clean_column"  is missing :  your test are added with line 327 test_that("when variables_to_clean is empty or null, check_with_list with still work"
- outputs should have this format when not binded. [1] "checked_dataset", "logical_xx" "logical_yy" (see test_that("Works with list of tests" line 50 and test_that("Inputs as list returns correct results" line 140)

**Comment by yannsay-impact** [comment]
[logical check](https://trello.com/c/C19hoRia/68-logical-check)

**Comment by mhkhan27** [comment]
1. I think the warning is coming from pivot longer. Using this `tidyr::pivot_longer(cols= -c("uuid", dplyr::all_of(variables_to_add)), names_to = "question", values_to = "old_value")` should remove the warning. 
2.  The following code in the test file is not doing anything. Just flagging if you wanted to something or not? 
 ```
 check_list2 <- data.frame(name = c("logical_xx", "logical_yy"),
                            log_name = c("logical_yy", "logical_yy"),
                            check = c("distance_to_market == \"less_30\" & access_to_market == \"no\"",
                                      "number_children_05 > 3"),
                            description = c("distance to market less than 30 and no access",
                                            "number of children under 5 seems high"),
                            variables_to_clean = c("distance_to_market, access_to_market",
                                                   "number_children_05"))
```
However I will merge now as it wont be changing anything!

**Pull request merged**
